<a href="https://colab.research.google.com/github/ProcessDoctor/MIT_ClassNote/blob/main/Test_of_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the libraries
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path= "/content/drive/MyDrive/Week 1  Foundations Python and Statistics/Dateset_ODI+-+Dateset_ODI.csv"
data=pd.read_csv(path)

In [ ]:
import numpy as np
a=np.array([1,10,2,0])
np.power(a,2)

array([  1, 100,   4,   0])

In [ ]:
import numpy as np
array=np.arange(10)

np.hsplit(array,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
import numpy as np
array1=np.array([1,0,0,1,0])
array2=np.arange(6)
#array1+array2

In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
data.dtypes

Scorecard     object
Team 1        object
Team 2        object
Winner        object
Margin        object
Ground        object
Match Date    object
dtype: object

In [ ]:
#checking missing values
data.isna().sum()
#or
#data.isnull().sum()

Scorecard       0
Team 1          0
Team 2          0
Winner          0
Margin        179
Ground          0
Match Date      0
dtype: int64

In [ ]:
fiftiethmatchwinner=data.iloc[49]['Winner']
print(fiftiethmatchwinner)

England

In [ ]:
devon=data[data['Ground']=='Devonport']
num_devon=len(devon)
print(num_devon)

1

In [ ]:
winner_Australia=(data['Winner']=='Australia').sum()

print(winner_Australia)

555

In [ ]:
winner_Team2=(data['Winner']==data['Team 2']).sum()

print(winner_Team2)

1637